import express from 'express';
import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';
import { PrismaPg } from "@prisma/adapter-pg";

dotenv.config();

// Initialize the Prisma Client
// It automatically finds the DATABASE_URL from your environment variables (.env file)
const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL + "?sslmode=no-verify"
});
const prisma = new PrismaClient({ adapter });
const app = express();
// The PORT is automatically set by Heroku when deployed
const PORT = process.env.PORT || 3000; 

// Middleware to parse JSON bodies
app.use(express.json());

// --- Routes ---

app.post('/menu-items', async (req, res) => {
  // Destructure the required fields, including the user-supplied restaurant_guid
  const { name, description, price, restaurant_guid } = req.body; 
  
  // Validate required fields
  if (!name || !price || !restaurant_guid) {
    return res.status(400).send('Name, price, and restaurant_guid are required.');
  }

  try {
    const newItem = await prisma.menuItem.create({
      data: {
        name,
        description,
        price: parseFloat(price), // Ensure price is a float
        restaurant_guid, // Pass the user-supplied UUID
        // 'guid' is automatically generated by the database
      },
    });
    // Respond with status 201 (Created)
    res.status(201).json(newItem);
  } catch (error) {
    // P2002 is the code for a unique constraint violation (e.g., name conflict)
    if (error.code === 'P2002') {
        return res.status(409).send('A menu item with this name already exists.');
    }
    console.error('Error creating menu item:', error);
    res.status(500).send('Could not create menu item.');
  }
});

app.get('/restaurants/:restaurantGuid/menu-items', async (req, res) => {
  const { restaurantGuid } = req.params;

  try {
    // Use findMany with a where clause to filter by the restaurant_guid
    const items = await prisma.menuItem.findMany({
      where: {
        restaurant_guid: restaurantGuid, // Filter items belonging to this GUID
      },
      // You can also order them, for example, by name
      orderBy: {
        name: 'asc',
      },
    });

    if (items.length === 0) {
      // It's common to return 200 with an empty array if no items are found
      // rather than 404, unless the restaurant itself is confirmed not to exist.
      return res.status(200).json([]); 
    }

    res.json(items);
  } catch (error) {
    console.error('Error fetching menu items by restaurant GUID:', error);
    res.status(500).send('Could not retrieve menu items for the restaurant.');
  }
});

app.get('/', (req, res) => {
  res.send('Server is running and connected to database via Prisma!');
});


// --- Start Server ---

async function startServer() {
  try {
    // Check database connection (optional, but good practice)
    await prisma.$connect(); 
    console.log('Database connection successful.');
    
    app.listen(PORT, () => {
      console.log(`\nServer is running on http://localhost:${PORT}`);
      console.log('Routes available: / and /menu-items (GET and POST)');
    });
  } catch (error) {
    console.error('Failed to connect to database or start server:', error);
    // Exit if the database connection fails
    process.exit(1); 
  } finally {
    // You might want to disconnect the client if the server shuts down, 
    // but typically Prisma clients manage connection pools internally.
  }
}

startServer();